# Makefile for the xburst sound oss driver
#
# 24 APR 2012, <jbbi: jbbi@ingernic.cn>
#

obj-$(CONFIG_JZ4780_INTERNAL_CODEC) += jz4780_codec.o jz4780_route_conf.o
obj-$(CONFIG_JZ4775_INTERNAL_CODEC) += jz4775_codec.o jz4775_route_conf.o
obj-$(CONFIG_M200_INTERNAL_CODEC_V12) += jz_codec_v12.o jz_route_conf_v12.o
obj-$(CONFIG_X1000_INTERNAL_CODEC_V13) += jz_codec_v13.o jz_route_conf_v13.o
obj-$(CONFIG_HDMI_JZ4780)			+= hdmi_virual_codec.o
obj-$(CONFIG_SOUND_JZ_SPDIF_V12)		+= hdmi_virual_codec.o
obj-$(CONFIG_SOUND_JZ_SPDIF_V13)		+= hdmi_virual_codec.o
obj-$(CONFIG_WM8594_CODEC_V12)			+= wm8594_codec_v12.o
obj-$(CONFIG_AKM4753_EXTERNAL_CODEC)		+= akm4753_codec_v13.o
obj-$(CONFIG_AKM4951_EXTERNAL_CODEC)		+= akm4951_codec_v13.o
obj-$(CONFIG_AKM4345_EXTERNAL_CODEC)		+= akm4345_codec_v13.o
obj-$(CONFIG_I2S_VIRUAL_EXTERNAL_CODEC) += i2s_virual_codec.o
