

obj-$(CONFIG_JZ_CIM)		+= jz_cim.o
obj-$(CONFIG_OV2650)		+= ov2650/
obj-$(CONFIG_OV3640)		+= ov3640/
obj-$(CONFIG_OV7675)		+= ov7675/
obj-$(CONFIG_OV2659_MODULE)		+= ov2659/
obj-$(CONFIG_OV5640)		+= ov5640/
obj-$(CONFIG_SP0838)		+= sp0838/
obj-$(CONFIG_GC0308)		+= gc0308/
obj-$(CONFIG_GC0308_Q8)		+= gc0308_q8/
obj-$(CONFIG_GC2015)		+= gc2015/
obj-$(CONFIG_HI253)		+= hi253/
obj-$(CONFIG_HI704)		+= hi704/
obj-$(CONFIG_FAKE)		+= fake/
obj-$(CONFIG_GT2005)              += gt2005/
obj-$(CONFIG_TVP5150)              += tvp5150/
obj-$(CONFIG_ADV7180)               += adv7180/
obj-$(CONFIG_GC0307)               += gc0307/
