
obj-y += board_base.o misc.o

obj-$(CONFIG_INPUT_KEYBOARD)   		+= keyboard_gpio.o
obj-$(CONFIG_SOUND) 			+= sound.o
obj-$(CONFIG_JZ_SPI) 			+= spi_bus.o
obj-$(CONFIG_JZ_SFC) 			+= spi_bus.o
obj-$(CONFIG_SPI_GPIO) 			+= spi_bus.o
obj-$(CONFIG_JZMMC_V12) 		+= mmc.o
obj-$(CONFIG_BCMDHD_1_141_66)    	+= ap6212_wlan_power_control.o ap6212_wlan_device.o
obj-$(CONFIG_BCM_AP6212_RFKILL)     	+= ap6212_bt_power_control.o ap6212_wlan_power_control.o
obj-$(CONFIG_REGULATOR_AXP173)		+= board-power-axp173.o
obj-$(CONFIG_I2C_GPIO)			+= i2c_bus.o
obj-y += lcd/
