#############################################################################
# Kbuild file for 'ZC0301 Image Processor and Control Chip' driver for Linux#
#                                                                           #
#  Copyright (C) 2006-2007 by Luca Risolia <luca.risolia@studio.unibo.it>   #
#                                                                           #
#  This program is free software; you can redistribute it and/or modify     #
#  it under the terms of the GNU General Public License as published by     #
#  the Free Software Foundation; either version 2 of the License, or        #
#  (at your option) any later version.                                      #
#                                                                           #
#  This program is distributed in the hope that it will be useful,          #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of           #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
#  GNU General Public License for more details.                             #
#                                                                           #
#  You should have received a copy of the GNU General Public License        #
#  along with this program; if not, write to the Free Software              #
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                #
#############################################################################

obj-m += zc0301.o
zc0301-objs := zc0301_core.o zc0301_pas202bcb.o zc0301_pb0330.o
