#
# Jz47xx Platform Support
#
snd-soc-jz47xx-objs := jz47xx-pcm.o
snd-soc-jz47xx-i2s-objs := jz47xx-i2s.o

obj-$(CONFIG_SND_JZ47XX_SOC) += snd-soc-jz47xx.o
obj-$(CONFIG_SND_JZ47XX_SOC_I2S) += snd-soc-jz47xx-i2s.o

# Jz4780 Machine Support
snd-soc-nc750-icdc-objs := nc750_icdc.o
snd-soc-mensa-icdc-objs := mensa_icdc.o

obj-$(CONFIG_SND_JZ4780_SOC_NC750_ICDC) += snd-soc-nc750-icdc.o
obj-$(CONFIG_SND_JZ4775_SOC_MENSA_ICDC) += snd-soc-mensa-icdc.o
