#define NAND_ALS	10
#define NAND_ALH	5
#define NAND_RP		25
#define NAND_WP		15
#define NAND_RHW	100
#define NAND_WHR	60
#define NAND_WHR2	200
#define NAND_RR		20
#define NAND_WB		100
#define NAND_ADL	100
#define NAND_CWAW	0
#define NAND_CS		25
#define NAND_CLH	5
#define NAND_WH		10
#define NAND_CH		5
#define NAND_DH		5
#define NAND_REH	10
